version: "3"
services:
  api:
    build: .
    ports:
      - 8088:8080
    volumes:
      - ./:/usr/src/app
    env_file:
        - ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: