version: "3"
services:
  app:
    build: .
    # ports:
    #   - 5000:5000
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
#     depends_on:
#       - postgres

#   postgres:
#     image: postgres:latest
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_PASSWORD=password123
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=fastapi
#     volumes:
#       - postgres-db:/var/lib/postgresql/data

# volumes:
#   postgres-db: