version: "3"
services:
  app:
    build: .
    # ports:
    #   - 5000:5000
    volumes:
      - ./:/usr/src/app
    env_file:
      - ./.env
    command: python -m app.main
#       - postgres

#   postgres:
#     image: postgres:latest
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_PASSWORD=password123
#       - POSTGRES_USER=postgres
#       - POSTGRES_DB=fastapi
#     volumes:
#       - postgres-db:/var/lib/postgresql/data

# volumes:
#   postgres-db: